### ISSUE TITLE
Remote and PGM

### ISSUE THREAD

**Issue by deon-wentzel** [e-mcgee/paradox_platform#6] opened 2017-05-17 04:45 UTC
Hi, another issue experienced is that the paradox remote does not work when the device is attached to the PGM, when plug-in is active. I have a front door gate that is attached to the PGM, so when the plug-in is active, the gate cannot be opened when using the remote. I am checking if the Paradox can be configured to allow more than one login.

**Comment by e-mcgee** [comment] 2017-06-09 21:57
I am trying to solve this one.  What I have noticed is that the paradox sometimes does not react to commands from the home app that controls the PGM.  However, the command is sent from my plugin.  It does mostly works for me.  I have a repeater installed to improve the signal which may be helping.  I have tried to make the code more resilient but the problem is there is no real time feedback to confirm that the command was successful or not.  The status is only read every 10 seconds and making the delay shorter just keeps the alarm too busy for any other commands to go trough.  I will see if there is anything I can do to improve.

**Comment by e-mcgee** [comment] 2017-08-28 22:32
I have implemented new code for the Garage door opener and am much happier with it.  It updates the initial state correctly now and is much more stable and responsive. I based it on an implementation of a plugin for a Raspberry Pi garage door opener.  It still does not update the final state of the garage door after opening or closing consistently which I am still working on, but overall I am much happier with the PGM control.  The current release is r129.

**Comment by deon-wentzel** [comment] 2017-09-01 09:00
Hi,
This resolve the PGM issue with the remotes.... Thanks for that. With the new code I can open the Garage door but not close the garage door as per Home App icon,  the plugin does not know if the garage door is open or close, I had to sync the Home Icon with the Garage Door. To resolve this I will install a sensor to determine if the garage door is open or closed. With the Gate I have a auto shut after 5 sec, so there is no issue there. What would be great is to have a option for a Gate Icon instead of Garage Door Icon.

**Comment by e-mcgee** [comment] 2017-09-01 23:39
Hi,
unfortunately Homekit does not seem to support a gate model yet, and only a garage door. 

I used the built in PGM zone with a magnetic switch to detect if door is open. That is the zone that my plugin then uses to detect if the door is open or closed.  It would be ideal to have two zones, one for fully open, and one for fully closed. Unfortunately the PGM has only one zone built in.

The status update to the Home app does not work consistently yet.  I am still trying to get it to update consistently.

**Comment by e-mcgee** [comment] 2017-09-01 23:52
Hi Deon,
I have published v130 that outputs the received messages from the alarm to the console.  If you could send me your console output with different alarm states on both partitions I could try to identify where the different partition status info is stored.

**Comment by MnrGreg** [comment] 2017-09-02 06:37
Hi guys,

HomeKit does have the Lock Accessory which might be more appropriate for a gate:
https://github.com/KhaosT/HAP-NodeJS/issues/265

**Comment by e-mcgee** [comment] 2017-09-04 05:23
Hi,

the Garage Door Opener is the best match for me at the moment as the gate behaviour is exactly the same as the garage door. It is just the icon that is not showing correctly. Hopefully Apple will model a gate opener soon.

**Closed as completed** 2017-09-26 13:20 UTC
